### ISSUE TITLE
[dng-dnm][1.1.1 develop] Consumes all available RAM then its get killed by system

### ISSUE THREAD

**Issue by stanedav** [denovogear/denovogear#234] opened 2017-08-28 07:26 UTC
Hello guys,

I have this issue with denovogear - I am using Ubuntu 16.04 and I tested this behaviour on two machines - one with 8 GB ram and second with 32 GB ram.
I am running this command:
`dng dnm auto --ped pedfile.ped --bcf bcffile.bcf -w output.vcf (tried also without -w and also with " > output.txt"`
After a while dng gets "Killed" by system, because all memory and swap is consumed. (I checked it on System monitor)...

- "Killed" is written in console
- no other program was running during performing analysis
- bcf file was created by "`samtools mpileup -gDf ref.fa bam1 bam2 bam3 > bcffile.bcf`"

Any ideas how to get dng run properly for whole bcf file? 

Thank you very much

**Comment by RodenLuo** [comment] 2017-10-17 03:10
so how did you solve this problem. I also met this

**Comment by reedacartwright** [comment] 2017-10-17 04:42
We need more details and a test case to identify the cause. @jgarc111

On Oct 16, 2017 8:10 PM, "RodenLuo" <notifications@github.com> wrote:

so how did you solve this problem. I also met this

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/denovogear/denovogear/issues/234#issuecomment-337104981>,
or mute the thread

**Comment by jgarciamesa** [comment] 2017-10-20 18:39
I have run the command with a local data set and I couldn't replicate the error. I would recommend to update to the newest version of DeNovoGear. It would also be helpful for us to run the same data set with `dng call` to see what the behaviour is. If the problem still persists, please send the header lines and the first couple lines of the bcf file in order the address the error.

**Comment by stanedav** [comment] 2018-01-12 09:13
Hi @reedacartwright, I would like to provide more details about this problem and try to solve it. I have prepared trio with bcf file (I have also bams available) and the latest version of dng. Do you think I can send you the data to test it? 

Thanks

**Comment by reedacartwright** [comment] 2018-01-12 19:33
Email me directly, and I will send you a dropbox location to upload your files.

**Comment by zhangjianruwang** [comment] 2018-01-22 08:41
I have a problem of  core dumped.
I tried many running environment and feel the problem is caused by BCF file format.
the command I use to produce BCF is:
"samtools mpileup -gDf ref.fa father.bam mother.bam brother1.bam brother2.bam sister1.bam > bcffile.bcf"
should I use only 1 offspring?

**Comment by reedacartwright** [comment] 2018-01-22 20:58
@zhangjianruwang, I moved your report to issue #250

**Comment by jgarciamesa** [comment] 2018-02-16 18:08
Hello @stanedav, I could not replicate your problem. However, I was able to detect and solve a memory leak on `dng dnm`. Once the changes are merged into our develop branch, I expect it to be soon, I encourage you to pull them and try to run the command again. I had no issues running the files you sent us, but if you encounter any problems let me know.

**Comment by stanedav** [comment] 2018-02-22 08:20
Hello @jgarc111 thank you, I would like to try the new develop version with fixed memory leak.
But I am getting this error after calling 
`sudo make install`

```
[  2%] Building CXX object src/lib/CMakeFiles/libdng.dir/ad.cc.o
In file included from /home/dnalab/bioinformatics/dng_022018/src/lib/../include/dng/io/ad.h:33:0,
                 from /home/dnalab/bioinformatics/dng_022018/src/lib/ad.cc:22:
/home/dnalab/bioinformatics/dng_022018/src/lib/../include/dng/io/file.h:89:18: error: field ‘file_’ has incomplete type ‘std::fstream {aka std::basic_fstream<char>}’
     std::fstream file_;
                  ^
In file included from /usr/include/c++/5/bits/localefwd.h:41:0,
                 from /usr/include/c++/5/string:43,
                 from /usr/include/c++/5/stdexcept:39,
                 from /usr/include/c++/5/array:38,
                 from /usr/include/c++/5/tuple:39,
                 from /usr/include/c++/5/unordered_map:41,
                 from /home/dnalab/bioinformatics/dng_022018/src/lib/../include/dng/depths.h:26,
                 from /home/dnalab/bioinformatics/dng_022018/src/lib/ad.cc:20:
/usr/include/c++/5/iosfwd:122:11: note: declaration of ‘std::fstream {aka class std::basic_fstream<char>}’
     class basic_fstream;
           ^
src/lib/CMakeFiles/libdng.dir/build.make:62: recipe for target 'src/lib/CMakeFiles/libdng.dir/ad.cc.o' failed
make[2]: *** [src/lib/CMakeFiles/libdng.dir/ad.cc.o] Error 1
CMakeFiles/Makefile2:365: recipe for target 'src/lib/CMakeFiles/libdng.dir/all' failed
make[1]: *** [src/lib/CMakeFiles/libdng.dir/all] Error 2
Makefile:160: recipe for target 'all' failed
make: *** [all] Error 2
```
Could you help me with this error? 

Thanks

**Comment by jgarciamesa** [comment] 2018-03-03 00:35
Hello @stanedav, we have fixed that issue. Please update to the latest version of our develop branch and build it. If there were any errors, let me know.

**Closed as completed** 2018-04-19 22:26 UTC
Labels: Fixed-in-Develop
