### ISSUE TITLE
Total number of Paired sample sites interrogated: 0

### ISSUE THREAD

**Issue by jielab** [denovogear/denovogear#279] opened 2018-06-27 18:46 UTC
**Hi, guys: I previously posted this question. I was really frustrated that it was not resolved, while I thought that my question is very very simple. I hope that this time i will get better luck. Basically, I have a trio, with 3 BAM files for them. I created a sample.ped file with the following content:**
1 18-CG-15-07932_S5_R1_001 0 0 1 0
1 18-CG-15-07931_S4_R1_001 0 0 2 0
1 18-CG-15-07930_S3_R1_001 18-CG-15-07932_S5_R1_001 18-CG-15-07931_S4_R1_001 1 1

**Then I run DNG with the following commands:**
module load samtools/1.8
samtools mpileup -t DP -gf /share/pkg/bwa/ref/hg19.fa ../bam/18-CG-15-07930_S3_R1_001.bam ../bam/18-CG-15-07931_S4_R1_001.bam ../bam/18-CG-15-07932_S5_R1_001.bam > trio.bcf
module load bcftools
bcftools view -Oz -o trio.vcf.gz trio.bcf
module load gcc/7.2.0
module load python/2.7.13
module load denovogear/2018-05-1_6723027
dng dnm auto --rd_cutoff 0 --ped sample.ped --bcf trio.bcf

**However, instead of getting any output, I got the following LOG file without anything else. Why at the end of this LOG file it says "Total number of Paired sample sites interrogated: 0". I am analyzing a trio, not a pair!!!**

[mpileup] 3 samples in 3 input files
<mpileup> Set max per-file depth to 2666

Created SNP lookup table
 First mrate: 1 last: 1
 First code: 6 last: 6
 First target string: AA/AA/AA last: TT/TT/TT
 First tref: 0.0002388 last: 0.99301

Created indel lookup table First code: 6 last: 6
 First target string: RR/RR/RR last: DD/DD/DD
 First prior: 0.05 last: 0.114

Created paired lookup table
 First target string: AA/AA last: TT/TT
 First prior 1 last: 1

Total number of SNP sites interrogated: 1122103115
Total number of SNP sites passing read-depth filters: 1122103115
Total number of INDEL sites interrogated: 604358
Total number of INDEL sites passing read-depth filters: 587646
Total number of Paired sample sites interrogated: 0
Total number of Paired sample sites passing read-depth filters: 0
Done !

**Comment by reedacartwright** [comment] 2018-06-27 20:36
It works as expected. `dng dnm` can process paired and trio samples in a single run. You get 0 Paired samples interrogated because you are using a trio. The SNP and INDEL reports refer to your trio. See below for the section of code responsible.

https://github.com/denovogear/denovogear/blob/ff2e50ffe1ff28dc9a9952a9c93561fb3c27561f/src/dng-dnm.cc#L313-L373

This is a duplicate of #266.

**Closed as completed by reedacartwright** 2018-06-27 20:36 UTC
Labels: duplicate, works-as-expected

**Comment by jielab** [comment] 2018-06-27 20:45
Dear Reed:

 

Sorry to bug you on this. If you say that “it works as expected”, where is the analysis results? I did not get any output except that LOG file. Again, I am expecting a report that lists all de-novo mutations based on my trio WES data.

 

Best regards,

Jie

**Comment by reedacartwright** [comment] 2018-06-27 21:01
For starters, you might not have any de novo mutations in your data. Try using `-c 0` to see if you get any calls.

**Comment by jielab** [comment] 2018-06-28 17:07
Dear Reed:

 

I now downloaded the latest version of DNG, and changed my sample to the new format as below. 

##PEDNG v1.0

#Individual Father Mother Sex Samples

18-CG-15-07932_S5_R1_001 . . male =

18-CG-15-07931_S4_R1_001 . . female =

18-CG-15-07930_S3_R1_001 18-CG-15-07932_S5_R1_001 18-CG-15-07931_S4_R1_001 male =

 

However, now when I run dng dnm auto --rd_cutoff 0 -c 0 --ped sample.ped --bcf trio.bcf, I got the following error:

BCF PARSING ERROR - Unable to find trio!

Members missing: 3!

Skipping site10008

 

Below, I use bcftools to show that these 3 samples specified in my sample file do exist.

bcftools query -l trio.bcf

18-CG-15-07930_S3_R1_001

18-CG-15-07931_S4_R1_001

18-CG-15-07932_S5_R1_001

 

 

Best regards,

Jie

**Comment by reedacartwright** [comment] 2018-06-28 17:33
The `dng dnm` program doesn't support the new ped format. It was designed for the newer `dng call` program.

**Comment by jielab** [comment] 2018-06-30 03:02
Dear Reed:

 

I now convert back to my old ped file then. Again, the ped file is pasted below. I am not sure that it is OK for me to use “1” as family ID for all 3 persons. 

1 18-CG-15-07932_S5_R1_001 0 0 1 0

1 18-CG-15-07931_S4_R1_001 0 0 2 0

1 18-CG-15-07930_S3_R1_001 18-CG-15-07932_S5_R1_001 18-CG-15-07931_S4_R1_001 1 1

 

Sorry that I have been taking too much of your time. I am not trying to do anything complicated at all. I simply want to use DNG to process a trio dataset and show me a list of variants that are potentially de-novo.

 

I first used the command samtools mpileup -t DP -gf hg19.fa 18-CG-15-07930_S3_R1_001.bam 18-CG-15-07931_S4_R1_001.bam 18-CG-15-07932_S5_R1_001.bam > trio.bcf to create the VCF file. 

 

Then I use dng dnm auto --rd_cutoff 0 -c 0 --ped sample.ped --bcf trio.bcf.

 

However, after I run the above two commands, I got NO output files. As you know, it is not possible that there are no de-novo variants in my WGS data. I manually checked the VCF file, and found a lot of variant with AA in father, AC in mother, while CG in proband. Variants like this should be caught as potentially do-novo correct?

 

As you saw, I have now spent more than 2 months struggling to make this thing work, which is supposed to be very simple. If somehow my data is corrupted, can you please point me to a nice example code and example dataset that analysis of trio works?

 

Thank you & best regards,

Jie

**Comment by reedacartwright** [comment] 2018-06-30 17:06
If you have manually identified sites that are de novos, please post the entire `#CHROM` header line and entire line from those positions so I can manually inspect them an figure out why they weren't being called.
