### ISSUE TITLE
Cmake build external not finding python

### ISSUE THREAD

**Issue by jgarciamesa** [denovogear/denovogear#122] opened 2016-03-16 17:27 UTC
I run:
cmake -DBUILD_EXTERNAL_PROJECTS=1 ..
error log:
CMake Error at /usr/local/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
  Could NOT find PythonLibs (missing: PYTHON_LIBRARIES PYTHON_INCLUDE_DIRS)
  (Required is at least version "2.7")
Call Stack (most recent call first):
  /usr/local/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:388 (_FPHSA_FAILURE_MESSAGE)
  /usr/local/share/cmake-3.5/Modules/FindPythonLibs.cmake:265 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  src/CMakeLists.txt:56 (find_package)

Python is not installed in this machine, build external failed

**Comment by jgarciamesa** [comment] 2016-03-16 17:33
Fixed with running:
sudo apt-get install python-dev
This is on ubuntu machine

**Comment by reedacartwright** [comment] 2016-03-16 18:45
Duplicate of #91

**Closed as completed** 2018-03-08 21:49 UTC
Labels: bug, Priority-Low
