### ISSUE TITLE
Build external on ubuntu doesn't support https

### ISSUE THREAD

**Issue by jgarciamesa** [denovogear/denovogear#123] opened 2016-03-16 17:56 UTC
Run cmake with build externals on ubuntu with the default cmake fails to download packages for eigen and htslib because the use of https instead of http

**Comment by kaeldai** [comment] 2016-03-16 18:35
Doesn't work when fetching cmake from the utopic library, or building cmake on ubuntu. The issue is with libcurl.

Will work when downloading and running the precompiled Linux x86_64 binary.

**Comment by reedacartwright** [comment] 2016-03-16 18:44
Duplicate of #19

**Closed as completed** 2016-03-28 07:46 UTC
Labels: bug
